### ISSUE TITLE
我觉得你是个计算机元老，但是年龄不大

### ISSUE THREAD

**Issue by Zhangyinshuai** [Pomotodo/api-doc#9]
偶然发现了这个文档， 然后看到你的博客https://orzfly.com/html/my-childhood-with-internet.html， 读了一遍确实感觉人与人环境不同，2004年读4年级，我2004年读一年级，相差不大，但是你的计算机编程之路也太早了。佩服啊。

**Comment by orzFly** [comment]
Sorry, but this issue tracker is about the documentation of Pomotodo Open API.
